# Generated by Django 4.1.5 on 2023-02-23 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='price',
            new_name='prices',
        ),
    ]
